In [81]:
from lens import *
from gr import *
import numpy as np
import matplotlib.pyplot as plt
%matplotlib widget 

In [73]:
a = np.array([[1,2,3,4,5],
          [1,2,3,6,7],
          [1,2,3,5,5]])
b = np.array([[1,2,5,4,2],
          [10,8,7,6,5],
          [3,4,6,5,1]])
c = np.array([[5,4,3,4,5],
          [2,1,6,6,3],
          [1,6,3,5,1]])
d = np.array([[2,1,3,4,7],
          [3,4,5,6,2],
          [7,6,4,5,4]])

In [74]:
np.diff([a,b,c,d], axis=0)

array([[[ 0,  0,  2,  0, -3],
        [ 9,  6,  4,  0, -2],
        [ 2,  2,  3,  0, -4]],

       [[ 4,  2, -2,  0,  3],
        [-8, -7, -1,  0, -2],
        [-2,  2, -3,  0,  0]],

       [[-3, -3,  0,  0,  2],
        [ 1,  3, -1,  0, -1],
        [ 6,  0,  1,  0,  3]]])

In [75]:
np.sum(np.diff([a,b,c,d], axis=0), axis=0)

array([[ 1, -1,  0,  0,  2],
       [ 2,  2,  2,  0, -5],
       [ 6,  4,  1,  0, -1]])

In [76]:
np.sum(np.sum(np.diff([a,b,c,d], axis=0), axis=0), axis=0)

array([ 9,  5,  3,  0, -4])

In [77]:
np.mean(np.array([a,b,c,d]),axis=0)

array([[2.25, 2.25, 3.5 , 4.  , 4.75],
       [4.  , 3.75, 5.25, 6.  , 4.25],
       [3.  , 4.5 , 4.  , 5.  , 2.75]])

In [78]:
a,b

(array([[1, 2, 3, 4, 5],
        [1, 2, 3, 6, 7],
        [1, 2, 3, 5, 5]]),
 array([[ 1,  2,  5,  4,  2],
        [10,  8,  7,  6,  5],
        [ 3,  4,  6,  5,  1]]))

In [79]:
np.sign(a-b)

array([[ 0,  0, -1,  0,  1],
       [-1, -1, -1,  0,  1],
       [-1, -1, -1,  0,  1]])

In [80]:
np.diff(np.sign(a-b))

array([[ 0, -1,  1,  1],
       [ 0,  0,  1,  1],
       [ 0,  0,  1,  1]])